---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/bazel version
      register: bazel_test_output
    - name: bazel version
      debug:
        msg: '{{ bazel_test_output.stdout }}'
