---
- name: Testing andrewrothstein.bazel
  hosts: all
  tasks:
    - name: Installing andrewrothstein.bazel
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'bazel version'
      ansible.builtin.command: /usr/local/bin/bazel version
      changed_when: false
      register: bazel_test_output
    - name: Output from 'bazel version'
      ansible.builtin.debug:
        msg: '{{ bazel_test_output.stdout }}'
